### ISSUE TITLE
bpy issue

### ISSUE THREAD

**Issue by yoon28** [gyhandy/3D-Copy-Paste#3]
which version of bpy did you use?
`bpy.ops.mesh.boundbox_add()` throw an error "AttributeError: Calling operator "bpy.ops.mesh.boundbox_add" error, could not be found".
This was occurred in bpy version 3.6.0, 3.5.0, 3.4.0.

**Comment by gyhandy** [comment]
I use blender3.0, and you can find how to add the function of the bounding box here:
https://blender.stackexchange.com/questions/14070/create-and-export-bounding-boxes-for-objects
